#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: canaima-bienvenido
# ARCHIVO: postinst
# DESCRIPCIÓN: Configura el sistema despues la instalación del paquete.
# COPYRIGHT:
#  (C) 2010 Luis Alejandro Martínez Faneyth <martinez.faneyth@gmail.com>
#  (C) 2010 Diego Alberto Aguilera Zambrano <daguilera85@gmail.com>
#  (C) 2010 Carlos Alejandro Guerrero Mora <guerrerocarlos@gmail.com>
#  (C) 2010 Francisco Javier Vásquez Guerrero <franjvasquezg@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

PKG="canaima-bienvenido"

case ${1} in

	configure)

	# Para cada usuario en /home/ ...
	for usuario in /home/*? ;
	do

		# Si existe la carpeta Escritorio
		if [ -d $usuario/Escritorio ]
		then

			# Obteniendo sólo el nombre del usuario
			usuario_min=$(basename ${usuario})

			# Y en caso de que el usuario sea un usuario activo (existente en /etc/shadow) ...
			case  $(grep ${usuario_min} /etc/shadow) in

				'')
				# No hace nada si no se encuentra en /etc/shadow
				;;

				*)
					
					echo '===== Instalando Canaima Bienvenido para el usuario "'$usuario_min'" ====='
					#Copiamos el lanzador de escritorio al escritorio de cada usuario
					cp /etc/skel/Escritorio/canaima-bienvenido.desktop /home/${usuario_min}/Escritorio/
					#con permisos apropiados
					chown ${usuario_min}:${usuario_min} /home/${usuario_min}/Escritorio/canaima-bienvenido.desktop

					#Asegurando que el directorio .config/autostart esté creado
					mkdir -p /home/${usuario_min}/.config/autostart/
					#con permisos apropiados
					chown ${usuario_min}:${usuario_min} /home/${usuario_min}/.config/autostart/

					#Copia del lanzador automático de canaima-bienvenido a cada usuario
					cp /etc/skel/.config/autostart/canaima-bienvenido-automatico.desktop /home/${usuario_min}/.config/autostart/
					#con permisos apropiados
					chown ${usuario_min}:${usuario_min} /home/${usuario_min}/.config/autostart/canaima-bienvenido-automatico.desktop

				;;
			esac
		fi
	done

	;;

        abort-upgrade|abort-remove|abort-deconfigure)
        ;;

        *)

                echo "postinst no reconoce el argumento '"${1}"'" >&2
                exit 1

        ;;

esac

#DEBHELPER#

exit 0
