#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: canaima-bienvenido
# ARCHIVO: postrm
# DESCRIPCIÓN: Revierte los cambios hechos por el paquete en los scripts del
#              mantenedor, de forma tal de asegurarse que el sistema quede
#              como estaba antes de su instalación.
# COPYRIGHT:
#  (C) 2010 Luis Alejandro Martínez Faneyth <martinez.faneyth@gmail.com>
#  (C) 2010 Diego Alberto Aguilera Zambrano <daguilera85@gmail.com>
#  (C) 2010 Carlos Alejandro Guerrero Mora <guerrerocarlos@gmail.com>
#  (C) 2010 Francisco Javier Vásquez Guerrero <franjvasquezg@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

case ${1} in

	purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

        # Para cada usuario en /home/ ...
        for usuario in /home/*? ;
        do

                # Si existe la carpeta Escritorio
                if [ -d $usuario/Escritorio ]
                then

                        # Obteniendo sólo el nombre del usuario
                        usuario_min=$(basename ${usuario})

                        # Y en caso de que el usuario sea un usuario activo (existente en /etc/shadow) ...
                        case  $(grep ${usuario_min} /etc/shadow) in

                                '')
                                # No hace nada si no se encuentra en /etc/shadow
                                ;;

                                *)

                                        echo '===== Removiendo Canaima Bienvenido para el usuario "'$usuario_min'" ====='
                                        # Removemos el lanzador del escritorio de cada usuario
                                        rm -f /home/${usuario_min}/Escritorio/canaima-bienvenido.desktop

                                        # Removemos el lanzador automático de canaima-bienvenido a cada usuario
                                        rm -f /home/${usuario_min}/.config/autostart/canaima-bienvenido-automatico.desktop

				;;
                        esac
                fi
        done

	;;

	*)

		echo "postrm no reconoce el argumento '"${1}"'" >&2
		exit 1
	;;

esac

#DEBHELPER#

exit 0
