#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: canaima-desarrollador
# ARCHIVO: postinst
# DESCRIPCIÓN: Configura el sistema despues la instalación del paquete.
# COPYRIGHT:
#  (C) 2010 Luis Alejandro Martínez Faneyth <martinez.faneyth@gmail.com>
#  (C) 2010 Diego Alberto Aguilera Zambrano <daguilera85@gmail.com>
#  (C) 2010 Carlos Alejandro Guerrero Mora <guerrerocarlos@gmail.com>
#  (C) 2010 Francisco Javier Vásquez Guerrero <franjvasquezg@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).


case ${1} in
	configure|'')
		# Para cada usuario en /home/ ...
		for USERNAME in $( ls -1 "/home/" ); do
			# Y en caso de que el usuario sea un usuario activo (existente en /etc/shadow) ...
			if [ $( grep -c "${USERNAME}:.*:.*:.*:.*:.*:::" /etc/shadow ) -eq 1 ] \
			&& [ $( grep -c "${USERNAME}:.*:.*:.*:.*:.*:/bin/.*sh" /etc/passwd ) -eq 1 ] \
			&& [ -d "/home/${USERNAME}/.config" ] && [ -d "/home/${USERNAME}/Escritorio" ]; then

				if [ ! -e /home/${USERNAME}/.config/canaima-desarrollador/usuario.conf ]; then
					ADVERTENCIA 'Instalando Canaima Desarrollador para el usuario "'${USERNAME}'"'

					# Asegurando que el directorio .config/canaima-desarrollador/ existe
					mkdir -p /home/${USERNAME}/.config/canaima-desarrollador/

					# Copia del archivo de configuración
					cp /etc/skel/.config/canaima-desarrollador/usuario.conf /home/${USERNAME}/.config/canaima-desarrollador/

					# con permisos apropiados
					chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}/.config/canaima-desarrollador/
				fi
			fi
		done
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)

		echo "postinst no reconoce el argumento '"${1}"'" >&2
		exit 1

	;;

esac

#DEBHELPER#

exit 0
